codlegal/appointments/urls.py
from django.urls import path

from appointments import views

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path("about/", views.AboutPage.as_view(), name="about"),
    path("practice-area/", views.PracticeAreaView.as_view(), name="practice_area"),
    path("appointments/book/", views.AppointmentCreateView.as_view(), name="appointment_create"),
    path("appointments/list/", views.UpcomingAppointmentListView.as_view(), name="appointment_list"),
    path("appointments/<int:pk>/delete/", views.AppointmentDeleteView.as_view(), name="appointment_delete"),
]

codlegal/codlegal/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("appointments.urls")),
    path("users/", include("users.urls")),
    path("reviews/", include("reviews.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += i18n_patterns(
#     path("admin/", admin.site.urls),
#     path("", include("appointments.urls")),
#     path("users/", include("users.urls")),
#     path("reviews/", include("reviews.urls"))
# )

codlegal/users/urls.py
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView
from django.urls import path

from users import views
from users.views import CustomLoginView

urlpatterns = [
    path("login/", CustomLoginView.as_view(template_name="users/login_with_django_form.html"), name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("password-change/", PasswordChangeView.as_view(template_name="users/password_change_form.html"), name="password_change"),
    path("password-change-done/", PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),
    path("password-reset/", PasswordResetView.as_view(template_name="users/password_reset_form.html"), name="password_reset"),
    path("password-reset-done/", PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<str:token>/", PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"), name="password_reset_confirm"),
    path("password-reset-complete/", PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name="password_reset_complete"),
    # path("signup/", views.signup, name="signup"),
    path("signup/advocate/", views.advocate_signup, name="advocate_signup"),
    path("signup/client/", views.client_signup, name="client_signup"),
    path("update/", views.update_account, name="update_account"),
    # path("advocates/<int:pk>/", views.AdvocateDetailView.as_view(), name="advocate_detail"),
    path("advocates/<int:pk>/", views.AdvocateDetailWithAppointmentFormView.as_view(), name="advocate_detail"),
    path("advocates/", views.AdvocateListView.as_view(), name="advocate_list"),
]

codlegal/appointments/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from users.models import User


# Create your models here.


class PracticeArea(models.Model):
    """
    Model for storing Practice Areas of Advocates
    """
    name = models.CharField(max_length=25, verbose_name='Name of Law')
    description = models.TextField()

    def __str__(self):
        return self.name

    def clean(self):
        name = self.name  # different from form.
        # if name == 'Test123':
        #     raise ValidationError({'name': 'This name is not allowed'})

    class Meta:
        verbose_name = _("Practice Area")
        verbose_name_plural = _("Practice Areas")
        db_table = "appointments_practicearea"
        constraints = [
            models.UniqueConstraint(name="pa_name_unq", fields=('name',)),
        ]


class Appointment(models.Model):
    client = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="+",
                               limit_choices_to={'role': User.RoleChoices.CLIENT})
    advocate = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="+",
                                 limit_choices_to={'role': User.RoleChoices.ADVOCATE})
    start_at = models.DateTimeField(_("Start At"))
    created_at = models.DateTimeField(default=timezone.now)

    def clean(self):
        if self.start_at < timezone.now():
            raise ValidationError({'start_at': 'Start Time should be of Future.'})

codlegal/reviews/models.py
from django.conf import settings
from django.db import models


# Create your models here.


class PlatformReview(models.Model):
    class SatisfactionChoices(models.IntegerChoices):
        VERY_SATISFIED = 5, 'Very Satisfied'
        SATISFIED = 4, 'Satisfied'
        NEUTRAL = 3, 'Neutral'
        UNSATISFIED = 2, 'Unsatisfied'
        VERY_UNSATISFIED = 1, 'Very Unsatisfied'

    satisfaction = models.PositiveSmallIntegerField("How satisfied are you with our Platform?", choices=SatisfactionChoices)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.TextField()

codlegal/appointments/forms.py
from django import forms

from appointments import models


class PracticeAreaForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for bound_field in self.visible_fields():
            if bound_field.field.widget.attrs.get('class'):
                bound_field.field.widget.attrs['class'] += ' form-control'
            else:
                bound_field.field.widget.attrs['class'] = 'form-control'

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data

    class Meta:
        model = models.PracticeArea
        fields = ('name', 'description')  # __all__

        # widgets = {
        #     'name': forms.TextInput(attrs={"class": "form-control"}),
        #     'description': forms.Textarea(attrs={"class": "form-control"})
        # }


class AppointmentCreateForm(forms.ModelForm):

    class Meta:
        model = models.Appointment
        fields = ['start_at']

codlegal/appointments/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView, TemplateView, ListView, DeleteView

from appointments import models, forms
from users.models import User


# Create your views here.

def home(request):
    context = {
        'practice_areas': models.PracticeArea.objects.all()
    }
    return render(request, "appointments/home.html", context=context)


class HomePage(TemplateView):
    template_name = "appointments/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['practice_areas'] = models.PracticeArea.objects.all()
        return context


def about(request):
    return render(request, "appointments/about.html")


class AboutPage(TemplateView):
    template_name = "appointments/about.html"
    extra_context = {
        'number': 1000000
    }


def practice_area(request):
    if request.method == "POST":
        form = forms.PracticeAreaForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('Practice Area Created')
        else:
            context = {
                "form": form
            }
            return render(request, "appointments/practice_area.html", context)
    else:
        context = {
            "form": forms.PracticeAreaForm()
        }
        return render(request, "appointments/practice_area.html", context)


class PracticeAreaView(CreateView):
    template_name = "appointments/practice_area.html"
    form_class = forms.PracticeAreaForm

    def get_success_url(self):
        return self.request.get_full_path()


class AppointmentCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = models.Appointment
    fields = ["advocate", "start_at"]
    success_message = "Appointment was created Successfully"

    def get_success_url(self):
        return reverse('home')

    def form_valid(self, form):
        form.instance.client = self.request.user
        return super().form_valid(form)


class UpcomingAppointmentListView(LoginRequiredMixin, ListView):
    model = models.Appointment
    paginate_by = 4
    ordering = ["start_at"]

    def get_queryset(self):
        queryset = super().get_queryset()
        logged_in_user = self.request.user
        if logged_in_user.role == User.RoleChoices.CLIENT:
            return queryset.filter(client=logged_in_user, start_at__gt=timezone.now())
        elif logged_in_user.role == User.RoleChoices.ADVOCATE:
            return queryset.filter(advocate=logged_in_user, start_at__gt=timezone.now())
        return queryset.none()


class AppointmentDeleteView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, DeleteView):
    model = models.Appointment
    success_url = reverse_lazy("appointment_list")
    success_message = "Appointment Deleted Successfully"
    permission_required = ["appointments.delete_appointment"]

    def has_permission(self):
        has_model_permission = super().has_permission()
        appointment = self.get_object()
        return has_model_permission and (
                    self.request.user == appointment.client or self.request.user == appointment.advocate)

codlegal/appointments/templates/base.html
{% load static %}
{% load i18n %}
<html>
<head>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>{%block title %} CodLegal {%endblock%}</title>
</head>

<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'appointments/logo.webp' %}" alt="" width="30"
                     height="24"
                     class="d-inline-block align-text-top">
                {% translate "CodLegal" %}
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="{% url 'home' %}">{% translate "Home" %}</a>
                    <a class="nav-link" href="{% url 'about' %}">{% translate "About"%}</a>
                    <a class="nav-link" href="{% url 'advocate_list' %}">{% translate "List Advocates"%}</a>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'login' %}">{% translate "Login"%}</a>
                    <a class="nav-link" href="{% url 'password_reset' %}">{% translate "Reset Password"%}</a>
                    {# <a class="nav-link" href="{% url 'signup' %}">{% translate "Signup"%}</a> #}

                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            {% translate "Signup"%}
                        </a>
                        <ul class="dropdown-menu dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'advocate_signup' %}">{% translate "Advocate"%}</a></li>
                            <li><a class="dropdown-item" href="{% url 'client_signup' %}">{% translate "Client"%}</a></li>
                        </ul>
                    </div>
                    {% else %}
                    <a class="nav-link" href="{% url 'appointment_list' %}">{% translate "My Appointments"%}</a>
                    <a class="nav-link" href="{% url 'update_account' %}">{% translate "My Account"%}</a>
                    <a class="nav-link" href="{% url 'password_change' %}">{% translate "Change Password"%}</a>
                    {% if perms.reviews %}
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink2" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            {% translate "Feedbacks"%}
                        </a>
                        <ul class="dropdown-menu dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink2">
                            {% if perms.reviews.add_platformreview %}
                            <li><a class="dropdown-item" href="{% url 'submit_app_review' %}">{% translate "Submit Feedback"%}</a></li>
                            {% endif %}
                            {% if perms.reviews.view_platformreview %}
                            <li><a class="dropdown-item" href="{% url 'view_app_reviews' %}">{% translate "View Feedbacks"%}</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    {% endif %}
                    <form action="{% url 'logout' %}" style="margin-bottom:0;" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="nav-link" style="background:none;border:none;">{% translate "Logout"%}</button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

<main>
    <div class="container vh-100 mt-5">
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div
                {% if message.tags %} class="alert {{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
        </div>
        {% endif %}
        {%block content %} CodLegal {%endblock%}
    </div>
</main>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>

</body>
</html>

codlegal/appointments/templates/field.html
{% load widget_tweaks %}
{% if field.use_fieldset %}
  <fieldset>
  {% if field.label %}{{ field.legend_tag }}{% endif %}
{% else %}
  {% if field.label %}{{ field.label_tag }}{% endif %}
{% endif %}


    {% if field.errors %}
      {{ field | add_class:"form-control is-invalid"}}
    {% else %}
      {{ field | add_class:"form-control" }}
    {% endif %}
    <div class="invalid-feedback">
        {{ field.errors }}
    </div>
{% if field.help_text %}<small class="form-text text-muted"{% if field.auto_id %} id="{{ field.auto_id }}_helptext"{% endif %}>{{ field.help_text|safe }}</small>{% endif %}
{% if field.use_fieldset %}</fieldset>{% endif %}

codlegal/appointments/templates/form.html
{% if errors and not fields %}
  <div>{% for field in hidden_fields %}{{ field }}{% endfor %}</div>
{% endif %}
{% for field, errors in fields %}
  <div class="mb-3">
    {{ field.as_field_group }}
    {% if forloop.last %}
      {% for field in hidden_fields %}{{ field }}{% endfor %}
    {% endif %}
</div>
{% endfor %}
{% if not fields and not errors %}
  {% for field in hidden_fields %}{{ field }}{% endfor %}
{% endif %}
{% for error in errors %}
  <div class="alert alert-warning">
    {{error}}
  </div>
{% endfor %}